# Generated by Django 3.2.5 on 2021-07-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
